# Maddy configuration file (v0.7+)
# Standard setup for DocNear (RxDesk)

$(hostname) = {env:MADDY_HOSTNAME}
$(primary_domain) = {env:MADDY_DOMAIN}
$(local_domains) = $(primary_domain)

# TLS Configuration
tls self_signed

# ----------------------------------------------------------------------------
# Global Modules

# This module provides both authentication and storage backend
sqlitedb local_db {
    driver sqlite3
    dsn /data/maddy.db
}

storage.imapsql local_mailboxes {
    driver sqlite3
    dsn /data/maddy.db
}

# ----------------------------------------------------------------------------
# Endpoints

submission submission {
    bind :587
    auth &local_db
    source $(primary_domain) {
        check {
            authorize_sender
        }
        destination postmaster {
             deliver_to &local_mailboxes
        }
        destination $(local_domains) {
             deliver_to &local_mailboxes
        }
        destination * {
             deliver_to &remote_queue
        }
    }
}

smtp mx_inbound {
    bind :25
    source * {
        destination postmaster {
             deliver_to &local_mailboxes
        }
        destination $(local_domains) {
             deliver_to &local_mailboxes
        }
        destination * {
             reject "Recipient address is not local"
        }
    }
}

imap imap_endpoint {
    bind :143
    auth &local_db
    storage &local_mailboxes
}

imap imaps_endpoint {
    bind :993
    auth &local_db
    storage &local_mailboxes
}

submission smtps_endpoint {
    bind :465
    auth &local_db
    source $(primary_domain) {
        check {
            authorize_sender
        }
        destination * {
             deliver_to &remote_queue
        }
    }
}

# ----------------------------------------------------------------------------

target.remote remote_queue {
    limits {
        max_conns 10
    }
}

log stderr
