services:
  stalwart:
    image: stalwartlabs/stalwart:latest
    container_name: mail_stalwart
    restart: unless-stopped
    hostname: mx.rxdesk.in
    networks:
      - stalwart-network
    ports:
      - "25:25"      # SMTP
      - "465:465"    # SMTPS
      - "587:587"    # Submission
      - "143:143"    # IMAP
      - "993:993"    # IMAPS
      - "4190:4190"  # ManageSieve
      - "8082:8080"  # Web Admin / Webmail
    volumes:
      - ./data:/opt/stalwart-mail

  # Add SnappyMail Webmail
  webmail:
    image: szupan/snappymail:latest
    container_name: snappymail
    restart: unless-stopped
    ports:
      - "8081:8888"
    networks:
      - stalwart-network
    volumes:
      - ./snappymail:/var/www/html/data

networks:
  stalwart-network:
    driver: bridge
